### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by vasilisvg** [larsdouweschuitema/minor-css-to-the-rescue#3]
Form ziet er netjes uit! Tof ook dat je duidelijke focus-styles op de inputs hebt gezet. 

- duidelijker focus styles ontbreken op de button en de link

**Comment by larsdouweschuitema** [comment]
Thanks for the feedback. Added focus to various elements. Made the navigation and form generic because of repetitive color use.

```css
nav li a:hover, nav li a:focus, form button[type="submit"]:hover, form button[type="submit"]:focus {
    background: #028566;
  }
```
